# fly.toml app configuration file generated for suparaise-agent-worker on 2025-07-20T18:16:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'suparaise-agent-worker'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1 # Set to 1 for production to keep the worker alive
  processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
